name: Deploy to Neocities

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Neocities does not need the special GitHub Pages permissions
permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Kiln
        run: |
          # Download the latest Linux binary
          curl -L -o kiln https://github.com/otaleghani/kiln/releases/latest/download/kiln_linux_amd64

          # Make it executable
          chmod +x kiln

      - name: Build Site
        run: ./kiln generate \ 
            --input "./" \ 
            --output "./public" \
            --url "https://whimsyscoundrel.neocities.org" \
            --name "Whimsy Scoundrel" \
            --font "lato"

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          # Add this secret in: Settings → Secrets and variables → Actions
          # Name: NEOCITIES_API_TOKEN   Value: your Neocities API key
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          dist_dir: public
          cleanup: true
